apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: app-c-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-c
  template:
    metadata:
      labels:
        app: app-c
    spec:
      containers:
        - name: app-c
          image: localhost:5000/fastapi_app
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 500m
              memory: 700Mi
            requests:
              cpu: 300m
              memory: 500Mi
          env:
            - name: PORT
              value: "8000"
            - name: APP_NAME
              value: app-c
            - name: MODE
              value: thrift-agent
            - name: AGENT_HOST_NAME
              value: jaeger-collector.istio-system.svc.cluster.local
            - name: AGENT_PORT
              value: "6831"
---
apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: app-c
spec:
  type: ClusterIP
  selector:
    app: app-c
  ports:
    - port: 8000
      targetPort: 8000
